# Generated by Django 3.2.10 on 2022-06-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterimg', '0002_alter_meter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='hotel_Main_Img',
            new_name='Meter_Main_Img',
        ),
    ]
