# Generated by Django 3.2.10 on 2022-06-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterimg', '0003_rename_hotel_main_img_meter_meter_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='Meter_Main_Img',
            new_name='meter_main_img',
        ),
    ]
