# Generated by Django 3.2.10 on 2022-06-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meterimg', '0004_rename_meter_main_img_meter_meter_main_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='meter_main_img',
            new_name='Meter_Main_Img',
        ),
    ]
