# Generated by Django 3.2.10 on 2022-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meterimg', '0005_rename_meter_main_img_meter_meter_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(upload_to='images_two/')),
            ],
        ),
    ]
